const works = [
  {
    project_name: "Smart Site Systems",
    company_name: "Skynotech",
    name: "skynotech smart site systems",
    desc: "a web application built for skynotech smart site systems.",
    link: "/projects/skynotech-smart-site-systems",
    asset: "/assets/images/projects/skynotech",
    banner: "1.webp",
    images: [
      { file: "1.webp", isWide: true },
      { file: "2.webp", isWide: false },
      { file: "3.webp", isWide: false },
      { file: "4.webp", isWide: false },
      { file: "5.webp", isWide: false },
      { file: "6.webp", isWide: true },
      { file: "7.webp", isWide: true },
    ],
  },
  {
    project_name: "Website",
    company_name: "Skynotech",
    name: "skynotech smart site systems website",
    desc: "a corporate website built for skynotech smart site systems.",
    link: "/projects/skynotech-smart-site-systems-website",
    techs: ["next.js", "firebase"],
    banner: "1.webp",
    asset: "/assets/images/projects/skynotech-website",
    images: [
      { file: "1.webp", isWide: true },
      { file: "2.webp", isWide: false },
      { file: "3.webp", isWide: false },
      { file: "4.webp", isWide: false },
      { file: "5.webp", isWide: false },
      { file: "6.webp", isWide: false },
      { file: "7.webp", isWide: false },
      { file: "8.webp", isWide: true },
    ],
  },
  {
    project_name: "Balıkesir Events",
    company_name: "Balıkesir Metropolitan Municipality",
    name: "balıkesir events mobile application",
    desc: "A dynamic mobile platform for Balıkesir's youth, offering real-time, personalized listings of all city events, concerts, and cultural activities.",
    link: "/projects/balikesir-etkinlik",
    asset: "/assets/images/projects/balikesir-etkinlik",
    banner: "1.gif",
    images: [
      { file: "1.webp", isWide: true },
      { file: "2.webp", isWide: false },
      { file: "3.webp", isWide: false },
      { file: "4.webp", isWide: true },
      { file: "5.webp", isWide: false },
      { file: "6.webp", isWide: false },
      { file: "7.webp", isWide: false },
      { file: "8.webp", isWide: false },
      { file: "9.webp", isWide: true },
      { file: "10.webp", isWide: true },
      { file: "11.webp", isWide: true },
    ],
  },
  {
    project_name: "Balıkesir İstihdam Ofisi",
    company_name: "Balıkesir Metropolitan Municipality",
    name: "balikesir istihdam ofisi",
    desc: "a job-search web application developed for the 'balıkesir istihdam ofisi'.",
    link: "/projects/balikesir-istihdam-ofisi",
    asset: "/assets/images/projects/balikesir-istihdam-ofisi",
    banner: "1.webp",
    images: [
      { file: "1.webp", isWide: true },
      { file: "2.webp", isWide: false },
      { file: "3.webp", isWide: false },
      { file: "4.webp", isWide: false },
      { file: "6.webp", isWide: false },
      { file: "5.webp", isWide: true },
    ],
  },
  {
    project_name: "BAPKA Official Website",
    company_name: "Balıkesir Planning and Development Agency",
    name: "balıkesir planning and development agency website",
    desc: "corporate website and web application for the BAPKA.",
    link: "/projects/bapka-website",
    asset: "/assets/images/projects/bapka-website",
    banner: "1.webp",
    images: [
      { file: "1.webp", isWide: true },
      { file: "2.webp", isWide: false },
      { file: "3.webp", isWide: false },
      { file: "4.webp", isWide: false },
      { file: "5.webp", isWide: false },
      { file: "6.webp", isWide: true },
    ],
  },
  {
    project_name: "Yakın Kart",
    company_name: "Balıkesir Metropolitan Municipality",
    name: "yakın kart mobile application",
    desc: "The digital face of social municipality, providing citizens with easy access to financial aid and transparent spending management.",
    link: "/projects/yakin-kart",
    asset: "/assets/images/projects/yakin-kart",
    banner: "1.webp",
    images: [
      { file: "1.webp", isWide: true },
      { file: "2.webp", isWide: false },
      { file: "3.webp", isWide: false },
      { file: "4.webp", isWide: false },
      { file: "5.webp", isWide: false },
      { file: "6.webp", isWide: false },
      { file: "7.webp", isWide: false },
      { file: "8.webp", isWide: true },
    ],
  },
  {
    project_name: "Askıda Fatura",
    company_name: "Balıkesir Metropolitan Municipality",
    name: "askıda fatura mobile application",
    desc: "A platform that digitizes anonymous aid. It allows users to pay utility bills for those in need, fostering community solidarity.",
    link: "/projects/askida-fatura",
    asset: "/assets/images/projects/askida-fatura",
    banner: "1.webp",
    images: [
      { file: "1.webp", isWide: true },
      { file: "2.webp", isWide: false },
      { file: "3.webp", isWide: false },
    ],
  },
  {
    project_name: "Can Dostlar",
    company_name: "Balıkesir Metropolitan Municipality",
    name: "candostlar mobile application",
    desc: "A dedicated app simplifying the process of rehoming stray animals, ensuring safe and transparent adoption within the community.",
    link: "/projects/can-dostlar",
    asset: "/assets/images/projects/can-dostlar",
    banner: "/assets/videos/can-dostlar.webm",
    images: [
      { file: "1.webp", isWide: true },
      { file: "2.webp", isWide: false },
      { file: "3.webp", isWide: false },
      { file: "4.webp", isWide: false },
      { file: "5.webp", isWide: false },
    ],
  },
  {
    project_name: "Balıkesir Eczane",
    company_name: "Balıkesir Metropolitan Municipality",
    name: "balıkesir eczane mobile application",
    desc: "A fast, reliable mobile guide showing the nearest on-duty pharmacies based on the user's real-time location and navigation support.",
    link: "/projects/balikesir-eczane",
    asset: "/assets/images/projects/balikesir-eczane",
    banner: "/assets/videos/balikesir-eczane.webm",
    images: [
      { file: "1.webp", isWide: true },
      { file: "2.webp", isWide: false },
      { file: "3.webp", isWide: false },
      { file: "4.webp", isWide: false },
      { file: "5.webp", isWide: false },
    ],
  },
];

export default works;
